### PR TITLE
Fix & Remove Delete leauge from dashboard #48

### PR DESCRIPTION
**Pull request by vikramnr**

### CODE REVIEW

**Comment by makkoli** [comment]
Your PR is failing our CI test due to linter errors. Make sure you do `npm run test` in the root directory to make sure that you are passing the linter and tests.

**Comment by vikramnr** [comment]
@makkoli  I'll have a look.

**Comment by makkoli** [comment]
I fixed it on the master branch. Pull master into your working branch and the the tests will pass.

**Comment by vikramnr** [comment]
Will Do

**Comment by vikramnr** [comment]
@makkoli  Hope this works

**Comment by makkoli** [comment]
Looks good, thanks bud.

**Pull request merged**
