### PR TITLE
Adding tape and some sample unit tests for models

### PR DESCRIPTION
**Pull request by lanesawyer**
I've added Tape. It's the unit testing framework used by the main FreeCodeCamp site, so I figured that would be a good choice. It's pretty straightforward to use, and I've enjoyed it so far!

Included are two samples of testing the models to make sure the have the right fields. If you think this would be useful, I can continue on testing all the other models as well, and we can expand the unit tests to other parts of the codebase after.

Here are the design decisions I've made that I wanted to run by you both to get your feedback:

- **I chose the pattern of adding a `__tests__` folder to each directory**, so that tests live near the code they are testing. It's a common pattern I've seen, but I'm open to switching it to something else (like a dedicated `tests` folder) if desired.
- **I've also added the `npm run test` command that will run all the test files** (which need to be named `_something_.test.js` in the `__tests__` folder).
- **Tests won't run if the linter doesn't pass**, so we'll have to make sure we fix the outstanding linter issues and keep those clean. Once we have TravisCI set up, it will be really easy to catch those issues on PRs.

Let me know if you'd like to take a different approach with any of the above!

### CODE REVIEW

**Comment by makkoli** [comment]
It seems like a very good choice! I like the idea of keeping tests in the directory of the code their testing. That would make the most sense to keep it grouped.

I do have a question though. I was looking through the docs for Tape and shouldn't we be using the babel supported version of it since we are using ES6 features? 

Also, I talked to `@CodeNonProfit` and he is going to talk to the guy that is in charge of maintaining all the repos of FCC and get TravisCI turned on for us.

**Comment by lanesawyer** [comment]
Good point on babel. I think since the tests are all on the Node side they work fine. But it would be good to set it up so the client side tests get compiled correctly when we have them. I'll take a look at it tomorrow and update the PR.

**Comment by lanesawyer** [comment]
So looking into it, I don't think we need the babel flag at this point. All the tests are being run in the Node environment, so the ES6 features in the test files will just work.

I tried running some tests in the client folder and it worked just fine, so my initial assumption was off (that's what happens when I try diagnosing something from bed haha)

I'm not 100 percent sure on the use case for the babel loader (perhaps for hot loading or for projects just using webpack and not Node, but we don't need that change at this point.

All this means this PR should be ready to go. If we have issues with the tests in the future we can fix it then, but for now it appears that they're running just fine without the flag.

**Comment by makkoli** [comment]
Sounds good, we are supposed to be getting another camper to help us with writing tests soon, so I'm glad we got this set up.

**Pull request merged**
